question_data = {"response_code": 0, "results": [
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Comics",
     "question": "In the webcomic Homestuck, the first character introduced is Dave Strider.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "Tony Hawk&#039;s Pro Skater was released in 1999.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                                       "question": "The commercial UK channel ITV stands for &quot;International Television&quot;.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Animals",
     "question": "Finnish Lapphund dogs were used for herding reindeer.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "medium", "category": "Geography",
                                       "question": "The capital of the US State Ohio is the city of Chillicothe.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Animals",
     "question": "An octopus can fit through any hole larger than its beak.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "medium", "category": "Mythology",
                                       "question": "The Roman god &quot;Jupiter&quot; was first known as &quot;Zeus&quot; to the Greeks.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Geography",
     "question": "The Southeast Asian island of Borneo is politically divided among 3 countries.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
     "question": "Fast food restaurant chains Carl&#039;s Jr. and Hardee&#039;s are owned by the same company.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
     "question": "Francis Bacon died from a fatal case of pneumonia while he was attempting to preserve meat by stuffing a chicken with snow.",
     "correct_answer": "True", "incorrect_answers": ["False"]}]}
